# Generated by Django 5.2.8 on 2026-01-08 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='created_by',
            new_name='recruiter',
        ),
    ]
