# Generated by Django 5.2.8 on 2026-01-08 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('recruiter', 'Recruiter'), ('jobseeker', 'Job Seeker')], default='jobseeker', max_length=20),
        ),
    ]
