# Generated by Django 5.2.8 on 2026-01-19 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('recruiter', 'Recruiter'), ('jobseeker', 'Job Seeker'), ('admin', 'Admin')], default='jobseeker', max_length=20),
        ),
    ]
